name: Relese new version

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install poetry

      - name: Build and publish module
        env:     # authentication
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          VERSION=$(echo ${{ github.ref }} | cut -d "v" -f 2 | xargs)
          echo "Change module version to $VERSION"
          poetry version $VERSION
          poetry build
          poetry publish -u "__token__" -p $PYPI_TOKEN
